CREATE TABLE CONTACTS
(
    ID         INT GENERATED BY DEFAULT AS IDENTITY,
    FIRST_NAME VARCHAR(50)  NOT NULL,
    LAST_NAME  VARCHAR(50)  NOT NULL,
    EMAIL      VARCHAR(255) NOT NULL,
    PHONE      VARCHAR(15),
    PRIMARY KEY (ID)
);

INSERT
INTO CONTACTS(FIRST_NAME, LAST_NAME, EMAIL, PHONE)
VALUES ('John', 'Doe', 'john.doe@example.com', NULL),
       ('Lily', 'Bush', 'lily.bush@example.com', '(408-234-2764)');

COMMIT;

select * from contacts;

select id, first_name, last_name, email, phone from contacts where phone is null;
select id, first_name, last_name, email, phone from contacts where phone is not null;




