SELECT *
FROM PAYMENT
WHERE AMOUNT = (SELECT AMOUNT FROM PAYMENT ORDER BY AMOUNT DESC LIMIT 1);

SELECT *
FROM PAYMENT
WHERE AMOUNT IN (SELECT AMOUNT FROM PAYMENT ORDER BY AMOUNT DESC LIMIT 1);

SELECT DISTINCT CUSTOMER_ID
FROM PAYMENT A
WHERE A.AMOUNT IN (SELECT K.AMOUNT FROM PAYMENT K ORDER BY K.AMOUNT DESC LIMIT 1);