SELECT *
FROM BASKET_A;

SELECT *
FROM BASKET_B;

SELECT A.ID ID_A, A.FRUIT FRUIT_A, B.ID ID_B, B.FRUIT FRUIT_B
FROM BASKET_A A
         INNER JOIN BASKET_B B ON A.FRUIT = B.FRUIT;

-- 한 명의 고객은 여러 건의 결제내역을 가질 수 있다.
-- 하나의 결제는 반드시 고객을 가져야 한다.
SELECT *
FROM CUSTOMER;

SELECT *
FROM PAYMENT;

SELECT COUNT(*)
FROM PAYMENT;


SELECT A.CUSTOMER_ID, A.FIRST_NAME, A.LAST_NAME, A.EMAIL, B.AMOUNT, B.PAYMENT_DATE
FROM CUSTOMER A
         INNER JOIN PAYMENT B ON A.CUSTOMER_ID = B.CUSTOMER_ID
WHERE A.CUSTOMER_ID = 2;

SELECT *
FROM STAFF;

SELECT A.CUSTOMER_ID,
       A.FIRST_NAME,
       A.LAST_NAME,
       A.EMAIL,
       B.AMOUNT,
       B.PAYMENT_DATE,
       C.FIRST_NAME AS S_FIRST_NAME,
       C.LAST_NAME  AS S_LAST_NAME
FROM CUSTOMER A
         INNER JOIN PAYMENT B ON A.CUSTOMER_ID = B.CUSTOMER_ID
         INNER JOIN STAFF C ON B.STAFF_ID = C.STAFF_ID;


